-- Seed: The United States Open 2026
-- Creates a new event instance and links the field from the global players table.
-- Also adds 57 new players to the global table idempotently, so this file is safe to run standalone on prod.
-- Usage: ./scripts/db.sh new-event seed_us_open_2026.sql <passkey>

BEGIN;

-- Ensure all US Open 2026 players exist in the global players table.
-- Idempotent via WHERE NOT EXISTS (no unique constraint on first_name/last_name).
INSERT INTO players (first_name, last_name, status, country_code)
SELECT v.first_name, v.last_name, v.status, v.country_code
FROM (VALUES
    ('Zac', 'Blair', 'professional', 'USA'),
    ('Laurie', 'Canter', 'professional', 'ENG'),
    ('Filippo', 'Celli', 'professional', 'ITA'),
    ('Hamilton', 'Coleman', 'amateur', 'USA'),
    ('Ugo', 'Coussaud', 'professional', 'FRA'),
    ('Ryder', 'Cowan', 'amateur', 'USA'),
    ('Cooper', 'Dossey', 'professional', 'USA'),
    ('Hennie', 'Du Plessis', 'professional', 'RSA'),
    ('Adrien', 'Dumont de Chassart', 'professional', 'BEL'),
    ('Marek', 'Fleming', 'amateur', 'USA'),
    ('Cole', 'Hammer', 'professional', 'USA'),
    ('Vaughn', 'Harber', 'amateur', 'USA'),
    ('Nick', 'Hardy', 'professional', 'USA'),
    ('Lucas', 'Herbert', 'professional', 'AUS'),
    ('Angel', 'Hidalgo', 'professional', 'ESP'),
    ('Robbie', 'Higgins', 'professional', 'USA'),
    ('J.B.', 'Holmes', 'professional', 'USA'),
    ('Ben', 'James', 'professional', 'USA'),
    ('Matthew', 'Jordan', 'professional', 'ENG'),
    ('T.K.', 'Kim', 'professional', 'USA'),
    ('Nathan', 'Kimsey', 'professional', 'ENG'),
    ('Jackson', 'Koivun', 'amateur', 'USA'),
    ('Chase', 'Kyes', 'amateur', 'USA'),
    ('Greyson', 'Leach', 'professional', 'USA'),
    ('Bryan', 'Lee', 'amateur', 'USA'),
    ('Eric', 'Lee', 'amateur', 'USA'),
    ('Graeme', 'McDowell', 'professional', 'NIR'),
    ('James', 'Nicholas', 'professional', 'USA'),
    ('Niklas', 'Norgaard', 'professional', 'DEN'),
    ('Ryuichi', 'Oiwa', 'professional', 'JPN'),
    ('Kaito', 'Onishi', 'professional', 'JPN'),
    ('Jackson', 'Ormond', 'amateur', 'USA'),
    ('Jake', 'Peacock', 'professional', 'USA'),
    ('Giuseppe', 'Puebla', 'amateur', 'USA'),
    ('Logan', 'Reilly', 'amateur', 'USA'),
    ('Rocco', 'Repetto Taylor', 'professional', 'ESP'),
    ('Matthew', 'Robles', 'amateur', 'USA'),
    ('Marcelo', 'Rozo', 'professional', 'COL'),
    ('Miles', 'Russell', 'amateur', 'USA'),
    ('Taihei', 'Sato', 'professional', 'JPN'),
    ('Jack', 'Schoenberger', 'professional', 'USA'),
    ('Manav', 'Shah', 'professional', 'USA'),
    ('Neal', 'Shipley', 'professional', 'USA'),
    ('Ben', 'Silverman', 'professional', 'CAN'),
    ('Jake', 'Sollon', 'professional', 'USA'),
    ('Jimmy', 'Stanger', 'professional', 'USA'),
    ('Preston', 'Stout', 'amateur', 'USA'),
    ('Jackson', 'Suber', 'professional', 'USA'),
    ('Caleb', 'Surratt', 'professional', 'USA'),
    ('Arni', 'Sveinsson', 'amateur', 'ISL'),
    ('Spencer', 'Tibbits', 'professional', 'USA'),
    ('Alejandro', 'Tosti', 'professional', 'ARG'),
    ('Peter', 'Uihlein', 'professional', 'USA'),
    ('Jackson', 'Van Paris', 'professional', 'USA'),
    ('Brandon', 'Wu', 'professional', 'USA'),
    ('Dylan', 'Wu', 'professional', 'USA'),
    ('Carl', 'Yuan', 'professional', 'CHN')
) AS v(first_name, last_name, status, country_code)
WHERE NOT EXISTS (
    SELECT 1 FROM players p
    WHERE p.first_name = v.first_name AND p.last_name = v.last_name
);

-- Create the event
INSERT INTO events (name, max_picks_per_team, max_teams_per_player, status, passkey, event_date, stipulations)
VALUES ('The United States Open 2026', 6, 1, 'not_started', :passkey, '2026-06-18 00:00:00-04'::timestamptz, '{"tournament": "US Open", "year": 2026}'::jsonb)
RETURNING id AS new_event_id;

-- Link players to the event by name
-- Uses a CTE to capture the new event ID
WITH new_event AS (
    SELECT id FROM events
    WHERE name = 'The United States Open 2026'
    ORDER BY id DESC LIMIT 1
)
INSERT INTO event_players (event_id, player_id)
SELECT new_event.id, p.id
FROM new_event, players p
WHERE (p.first_name, p.last_name) IN (
    ('Ludvig', 'Aberg'),
    ('Daniel', 'Berger'),
    ('Akshay', 'Bhatia'),
    ('Zac', 'Blair'),
    ('Keegan', 'Bradley'),
    ('Michael', 'Brennan'),
    ('Jacob', 'Bridgeman'),
    ('Sam', 'Burns'),
    ('Laurie', 'Canter'),
    ('Patrick', 'Cantlay'),
    ('Bud', 'Cauley'),
    ('Filippo', 'Celli'),
    ('Wyndham', 'Clark'),
    ('Hamilton', 'Coleman'),
    ('Corey', 'Conners'),
    ('Pierceson', 'Coody'),
    ('Ugo', 'Coussaud'),
    ('Ryder', 'Cowan'),
    ('Jason', 'Day'),
    ('Bryson', 'DeChambeau'),
    ('Cooper', 'Dossey'),
    ('Hennie', 'Du Plessis'),
    ('Adrien', 'Dumont de Chassart'),
    ('Nico', 'Echavarria'),
    ('Harris', 'English'),
    ('Ethan', 'Fang'),
    ('Alex', 'Fitzpatrick'),
    ('Matt', 'Fitzpatrick'),
    ('Tommy', 'Fleetwood'),
    ('Marek', 'Fleming'),
    ('Rickie', 'Fowler'),
    ('Ryan', 'Fox'),
    ('Ryan', 'Gerard'),
    ('Chris', 'Gotterup'),
    ('Max', 'Greyserman'),
    ('Ben', 'Griffin'),
    ('Emiliano', 'Grillo'),
    ('Harry', 'Hall'),
    ('Cole', 'Hammer'),
    ('Vaughn', 'Harber'),
    ('Nick', 'Hardy'),
    ('Brian', 'Harman'),
    ('Padraig', 'Harrington'),
    ('Tyrrell', 'Hatton'),
    ('Russell', 'Henley'),
    ('Lucas', 'Herbert'),
    ('Jackson', 'Herrington'),
    ('Angel', 'Hidalgo'),
    ('Robbie', 'Higgins'),
    ('Harry', 'Higgs'),
    ('Ryo', 'Hisatsune'),
    ('Nicolai', 'Hojgaard'),
    ('J.B.', 'Holmes'),
    ('Brandon', 'Holtz'),
    ('Billy', 'Horschel'),
    ('Viktor', 'Hovland'),
    ('Mason', 'Howell'),
    ('Sungjae', 'Im'),
    ('Ben', 'James'),
    ('Dustin', 'Johnson'),
    ('Matthew', 'Jordan'),
    ('Johnny', 'Keefer'),
    ('Michael', 'Kim'),
    ('Si Woo', 'Kim'),
    ('T.K.', 'Kim'),
    ('Tom', 'Kim'),
    ('Nathan', 'Kimsey'),
    ('Chris', 'Kirk'),
    ('Kurt', 'Kitayama'),
    ('Jake', 'Knapp'),
    ('Brooks', 'Koepka'),
    ('Ben', 'Kohles'),
    ('Jackson', 'Koivun'),
    ('Chase', 'Kyes'),
    ('Greyson', 'Leach'),
    ('Bryan', 'Lee'),
    ('Eric', 'Lee'),
    ('Min Woo', 'Lee'),
    ('Shane', 'Lowry'),
    ('Robert', 'MacIntyre'),
    ('Hideki', 'Matsuyama'),
    ('Matt', 'McCarty'),
    ('Graeme', 'McDowell'),
    ('Max', 'McGreevy'),
    ('Rory', 'McIlroy'),
    ('Maverick', 'McNealy'),
    ('Keith', 'Mitchell'),
    ('Taylor', 'Montgomery'),
    ('Collin', 'Morikawa'),
    ('William', 'Mouw'),
    ('James', 'Nicholas'),
    ('Joaquin', 'Niemann'),
    ('Alex', 'Noren'),
    ('Niklas', 'Norgaard'),
    ('Andrew', 'Novak'),
    ('Ryuichi', 'Oiwa'),
    ('Kaito', 'Onishi'),
    ('Jackson', 'Ormond'),
    ('Carlos', 'Ortiz'),
    ('John', 'Parry'),
    ('Jake', 'Peacock'),
    ('Chandler', 'Phillips'),
    ('J.T.', 'Poston'),
    ('Giuseppe', 'Puebla'),
    ('David', 'Puig'),
    ('Mateo', 'Pulcini'),
    ('Andrew', 'Putnam'),
    ('Jon', 'Rahm'),
    ('Aaron', 'Rai'),
    ('Patrick', 'Reed'),
    ('Logan', 'Reilly'),
    ('Kristoffer', 'Reitan'),
    ('Rocco', 'Repetto Taylor'),
    ('Matthew', 'Robles'),
    ('Patrick', 'Rodgers'),
    ('Justin', 'Rose'),
    ('Kevin', 'Roy'),
    ('Marcelo', 'Rozo'),
    ('Miles', 'Russell'),
    ('Adrien', 'Saddier'),
    ('Taihei', 'Sato'),
    ('Jayden', 'Schaper'),
    ('Xander', 'Schauffele'),
    ('Scottie', 'Scheffler'),
    ('Matti', 'Schmid'),
    ('Jack', 'Schoenberger'),
    ('Adam', 'Scott'),
    ('Manav', 'Shah'),
    ('Neal', 'Shipley'),
    ('Ben', 'Silverman'),
    ('Alex', 'Smalley'),
    ('Cameron', 'Smith'),
    ('Jake', 'Sollon'),
    ('J.J.', 'Spaun'),
    ('Jordan', 'Spieth'),
    ('Jimmy', 'Stanger'),
    ('Sam', 'Stevens'),
    ('Preston', 'Stout'),
    ('Sepp', 'Straka'),
    ('Jackson', 'Suber'),
    ('Caleb', 'Surratt'),
    ('Arni', 'Sveinsson'),
    ('Nick', 'Taylor'),
    ('Sahith', 'Theegala'),
    ('Justin', 'Thomas'),
    ('Davis', 'Thompson'),
    ('Spencer', 'Tibbits'),
    ('Alejandro', 'Tosti'),
    ('Peter', 'Uihlein'),
    ('Jackson', 'Van Paris'),
    ('Gary', 'Woodland'),
    ('Brandon', 'Wu'),
    ('Dylan', 'Wu'),
    ('Sudarshan', 'Yellamaraju'),
    ('Cameron', 'Young'),
    ('Carl', 'Yuan')
);

COMMIT;

-- Summary
\echo ''
\echo '=== New Event Created ==='
SELECT id, name, passkey, max_picks_per_team, status
FROM events ORDER BY id DESC LIMIT 1;

SELECT COUNT(*) AS players_linked
FROM event_players
WHERE event_id = (SELECT id FROM events ORDER BY id DESC LIMIT 1);
